name: HelloWorld


on: push


jobs: 
  hello-world: 

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@3
    - name: Running hello
      run: "echo Hello World"
    - name: Running linux version
      run:
        echo Running on Linux
        uname -a
        

      
